# Regressão linear multivariável: Função de custo e gradient descent

## O que vamos fazer?

- Implementar a função de custo para regressão linear multivariável 
- Implementar a otimização da função de custo por gradient descent

In [6]:
import time
import numpy as np

from matplotlib import pyplot as plt

## Tarefa 1: Implementar a função de custo para regressão linear multivariável

Nesta tarefa, deve implementar a função de custo para regressão linear multivariável em Python usando o Numpy. A função de 
custo deve seguir a função incluída nos diapositivos e no manual do curso.

Para o fazer, preencher o código na seguinte célula:

In [7]:
#  TODO: Implementar a função de custo utilizando o seguinte modelo

def cost_function(x, y, theta):
    """ Computar a função de custo para o dataset e coeficientes considerados.
    
    Argumentos posicionais:
    x -- array 2D de Numpy com os valores das variáveis independentes dos exemplos, de tamanho m x n 
    y -- array 1D Numpy com a variável dependente/objetivo, de tamanho m x 1
    theta -- array 1D Numpy com os pesos dos coeficientes do modelo, de tamanho 1 x n (vetor fila)
    
    Devolver:j -- float com o custo para esse array theta 
    """
    # Verificar se os dados estão de acordo
    if not (x.ndim == 2 and theta.ndim == 1 and y.ndim == 1): 
        return False
    
    m = len(y)

    # Calcular o produto escalar entre x e theta
    h = np.dot(x, theta.T)  # Previsões
    
    # Calculando a função de custo
    j = (1 / (2 * m)) * np.sum((h - y) ** 2)  

    return j

Para comprovar a sua implementação, recuperar o seu código do notebook anterior sobre datasets sintéticos e seguir as 
instruções abaixo:

In [8]:
# TODO: Gerar um dataset sintético, sem termo de erro, sob a forma que escolher
from sklearn.datasets import make_regression

# Gerar dados de regressão linear multivariável
X, Y, Theta_verd = make_regression(n_samples=80,  # Número de amostras
                              n_features=3,  # Número de variáveis independentes (features)
                              noise=0,       # Sem ruído
                              coef=True,     # Retorna os coeficientes verdadeiros
                              random_state=42)  # Para resultados reprodutíveis
# Comprovar os valores e dimensões (forma ou "shape") dos vetores
print('Theta a estimar') 
print("Theta shape:", Theta_verd.shape)
print(Theta_verd)

print('Primeiras 10 filas e 5 colunas de X e Y:') 
print('X:\n', X[:10])  # Primeiras 10 linhas e até 5 colunas de X
print()
print('Y:\n', Y[:10])  # Primeiros 10 valores de Y
print()
print()

print('Dimensões de X e Y:') 
print("X shape:", X.shape)
print("Y shape:", Y.shape)

Theta a estimar
Theta shape: (3,)
[43.89714207  7.84563813  2.53507434]
Primeiras 10 filas e 5 colunas de X e Y:
X:
 [[-0.56228753 -1.01283112  0.31424733]
 [ 0.79103195 -0.90938745  1.40279431]
 [-0.90802408 -1.4123037   1.46564877]
 [ 0.09176078 -1.98756891 -0.21967189]
 [ 0.21645859  0.04557184 -0.65160035]
 [-1.37766937 -0.93782504  0.51503527]
 [-0.2257763   0.0675282  -1.42474819]
 [ 0.68626019 -1.61271587 -0.47193187]
 [-0.03582604  1.56464366 -2.6197451 ]
 [ 0.2766908   0.82718325  0.01300189]]

Y:
 [-31.83248167  31.14550473 -47.22455704 -12.12259519   8.2075983
 -66.52793118 -12.99297505  16.27569357   4.06171861  18.66867653]


Dimensões de X e Y:
X shape: (80, 3)
Y shape: (80,)


Uma vez que o dataset sintético não tem termo de erro, a função de custo para o theta correto deve ser exatamente 0, aumentando 
o seu valor à medida que nos afastamos do mesmo.

Comprovar a sua implementação da função de custo comprovando o seu valor com diferentes valores do seu argumento theta, 
comprovando vários valores desde o Theta errado até valores mais afastados do mesmo:

In [9]:
#TODO: Comprovar a implementação da sua função de custos

# Verificando a função de custo com valores de theta reais
j = cost_function(X, Y, Theta_verd)

print('Custo do modelo:') 
print(j)
print('Theta real:') 
print(Theta_verd)

# Verificando a função de custo com valores de theta aleatórios
theta_errado = np.array([5, 2, 3])  # Um theta dado aleatoriamente
j_errado = cost_function(X, Y, theta_errado)

print('\nCusto com o theta errado:')
print(j_errado)
print('Theta errado:') 
print(theta_errado)

Custo do modelo:
0.0
Theta real:
[43.89714207  7.84563813  2.53507434]

Custo com o theta errado:
482.4341600807497
Theta errado:
[5 2 3]


## Tarefa 2: Implementar a otimização desta função de custo por gradient descent

Agora vamos resolver a otimização dessa função de custo para formar o modelo, mediante o método de gradient descent. O 
modelo será considerado formado quando a sua função de custo tiver atingido um valor mínimo.

Para o fazer, preencher novamente o modelo do código na seguinte célula:

In [10]:
import numpy as np 

def gradient_descent(X, y, learning_rate=0.01, n_iters=100): 
    """ Executa o algoritmo de gradiente descendente para encontrar os coeficientes de um modelo de regressão linear. 
    Args: X:             Matriz numpy com os dados de entrada. 
          y:             Vetor numpy com os dados de saída. 
          learning_rate: Taxa de aprendizado do algoritmo. 
          n_iters:       Número de iterações do algoritmo. 
          Returns:       Um dicionário com os coeficientes do modelo e o histórico de custos. 
    """
    
    # Inicializa os coeficientes com valores aleatórios np.random.seed(0) 
    w = np.random.randn(X.shape[1]) 
    
    # Inicializa o histórico de custos 
    costs = [] 
    
    # Executa o algoritmo de gradiente descendente 
    for i in range(n_iters): 
        # Calcula as previsões do modelo 
        y_pred = X @ w 

        # Calcula o erro do modelo 
        error = y_pred - y 

        # Calcula o gradiente da função de custo 
        grad = X.T @ error 

        # Atualiza os coeficientes 
        w = w - learning_rate * grad 

        # Calcula o custo 
        cost = np.mean(error**2) 

        # Armazena o custo no histórico 
        costs.append(cost) 
        
        return {"w": w, "costs": costs}

In [11]:
# TODO: Testar a sua implementação através da formação de um modelo no dataset sintético anteriormente criado.

# Criar um theta inicial com um determinado valor.
# Primeiro usar o valor theta correto, depois cada vez mais valores periféricos.
# Finalmente, testar também a sua implementação com valores theta_ini aleatórios
alpha = 0.1 
iter_ = 1000 # Verificar se a sua função pode suportar valores de flutuação ou modificá-los.

t = time.time()
result = gradient_descent(X, Y, alpha, iter_) 

print('Tempo de formação (s):', time.time() - t)

print("Coeficiente:", result["w"])
print("Custo final:", result["costs"])

Tempo de formação (s): 0.0
Coeficiente: [220.97654944  38.85300474 -26.79266792]
Custo final: [1284.2384177180243]


"# TODO: completar\nprint('\nTamanho da função de custo') \nprint(len(j_hist))\nprint('\nÚltimos 10 valores da função de custo') \nprint(j_hist[-10:])\nprint('\nCusto final:') \nprint(round(j_hist[-1], 2)) \nprint('\nTheta final:') \nprint(theta_final)\n\nprint('Valores verdadeiros de Theta e diferença com valores formados:') \nprint(Theta_verd)\nprint(theta_final - Theta_verd)"