In [1]:
import numpy as np
import pandas as pd
import urllib
import sklearn
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
sms_spam = pd.read_csv('smsspamcollection/SMSSpamCollection',sep='\t', header=None, names=['Label', 'SMS'])

print(sms_spam.shape)
sms_spam.head()

(5572, 2)


Label                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
dataset = np.loadtxt('spambase/spambase.data', delimiter=",")
print(dataset[0])
print(dataset.shape)

[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.      1.   ]
(4601, 58)


In [19]:
x = dataset[:, :-1]
y = dataset[:, -1]

print(x)
print(y)
print(x[0])

[[0.000e+00 6.400e-01 6.400e-01 ... 3.756e+00 6.100e+01 2.780e+02]
 [2.100e-01 2.800e-01 5.000e-01 ... 5.114e+00 1.010e+02 1.028e+03]
 [6.000e-02 0.000e+00 7.100e-01 ... 9.821e+00 4.850e+02 2.259e+03]
 ...
 [3.000e-01 0.000e+00 3.000e-01 ... 1.404e+00 6.000e+00 1.180e+02]
 [9.600e-01 0.000e+00 0.000e+00 ... 1.147e+00 5.000e+00 7.800e+01]
 [0.000e+00 0.000e+00 6.500e-01 ... 1.250e+00 5.000e+00 4.000e+01]]
[1. 1. 1. ... 0. 0. 0.]
[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.   ]


In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [21]:
MultiNB = MultinomialNB()
MultiNB.fit(x_train, y_train)

y_predict = MultiNB.predict(x_test)
accuracy_score(y_test, y_predict)

0.7735352205398288

In [23]:
from sklearn.naive_bayes import GaussianNB

gNB = GaussianNB()
gNB.fit(x_train, y_train)

y_predict = gNB.predict(x_test)
accuracy_score(y_test, y_predict)

0.8209348255431205

In [26]:
from sklearn.naive_bayes import ComplementNB

cNB = ComplementNB()
cNB.fit(x_train, y_train)

y_predict = cNB.predict(x_test)
accuracy_score(y_test, y_predict)

0.7741935483870968

In [27]:
from sklearn.naive_bayes import BernoulliNB

bNB = BernoulliNB()
bNB.fit(x_train, y_train)

y_predict = bNB.predict(x_test)
accuracy_score(y_test, y_predict)

0.8933508887425938