In [24]:
import numpy as np

from matplotlib import pyplot as plt

In [42]:
# TODO: Gerar um dataset sintético, sem termo de erro, sob a forma que escolher
from sklearn.datasets import make_regression

# Gerar dados de regressão linear multivariável
X, Y, Theta_verd = make_regression(n_samples=80,  # Número de amostras
                              n_features=3,  # Número de variáveis independentes (features)
                              noise=0,       # Sem ruído
                              coef=True,     # Retorna os coeficientes verdadeiros
                              random_state=42)  # Para resultados reprodutíveis

# Comprovar os valores e dimensões (forma ou "shape") dos vetores
print('Theta a estimar') 
print("Theta shape:", Theta_verd.shape)
print(Theta_verd)


print('Primeiras 10 filas e 5 colunas de X e Y:') 
print('X:\n', X[:10])  # Primeiras 10 linhas e até 5 colunas de X
print()
print('Y:\n', Y[:10])  # Primeiros 10 valores de Y
print()
print()
X[:, 0] = X[:, 0] * 50
X[:, 1] = X[:, 1] ** 3
X[:, 2] = X[:, 2] * 20 
 
print('Primeiras 10 filas e 5 colunas de X e Y:') 
print('X:\n', X[:10])  # Primeiras 10 linhas e até 5 colunas de X

print("X shape:", X.shape)
print("Y shape:", Y.shape)

Theta a estimar
Theta shape: (3,)
[43.89714207  7.84563813  2.53507434]
-----------
(80, 3) (80,) (3,)
-----------
Primeiras 10 filas e 5 colunas de X e Y:
X:
 [[-0.56228753 -1.01283112  0.31424733]
 [ 0.79103195 -0.90938745  1.40279431]
 [-0.90802408 -1.4123037   1.46564877]
 [ 0.09176078 -1.98756891 -0.21967189]
 [ 0.21645859  0.04557184 -0.65160035]
 [-1.37766937 -0.93782504  0.51503527]
 [-0.2257763   0.0675282  -1.42474819]
 [ 0.68626019 -1.61271587 -0.47193187]
 [-0.03582604  1.56464366 -2.6197451 ]
 [ 0.2766908   0.82718325  0.01300189]]

Y:
 [-31.83248167  31.14550473 -47.22455704 -12.12259519   8.2075983
 -66.52793118 -12.99297505  16.27569357   4.06171861  18.66867653]


Primeiras 10 filas e 5 colunas de X e Y:
X:
 [[-2.81143765e+01 -1.03898939e+00  6.28494665e+00]
 [ 3.95515974e+01 -7.52050278e-01  2.80558862e+01]
 [-4.54012038e+01 -2.81698343e+00  2.93129754e+01]
 [ 4.58803883e+00 -7.85175225e+00 -4.39343776e+00]
 [ 1.08229295e+01  9.46432595e-05 -1.30320070e+01]
 [-6.88834

In [37]:
#  TODO: Implementar a função de custo utilizando o seguinte modelo

def cost_function(x, y, theta):
    """ Computar a função de custo para o dataset e coeficientes considerados.
    
    Argumentos posicionais:
    x -- array 2D de Numpy com os valores das variáveis independentes dos exemplos, de tamanho m x n 
    y -- array 1D Numpy com a variável dependente/objetivo, de tamanho m x 1
    theta -- array 1D Numpy com os pesos dos coeficientes do modelo, de tamanho 1 x n (vetor fila)
    
    Devolver:j -- float com o custo para esse array theta 
    """
    # Verificar se os dados estão de acordo
    if not (x.ndim == 2 and theta.ndim == 1 and y.ndim == 1): 
        return False
    
    m = len(y)

    # Calcular o produto escalar entre x e theta
    h = np.dot(x, theta.T)  # Previsões
    
    # Calculando a função de custo
    j = (1 / (2 * m)) * np.sum((h - y) ** 2)  

    return j

In [38]:
# TODO: Implementar a função que forma o modelo por gradient descent
import math

def gradient_descent(x, y, theta, alpha, e=1e-6, iter=8000):
    """ Formar o modelo otimizando a sua função de custo por gradient descent
    
    Argumentos posicionais:
    x -- array 2D de Numpy com os valores das variáveis independentes dos exemplos, de tamanho m x n 
    y -- array 1D Numpy com a variável dependente/objetivo, de tamanho m x 1
    theta -- array 1D Numpy com os pesos dos coeficientes do modelo, de tamanho 1 x n (vetor fila) 
    alpha -- float, ratio de formação
    
    Argumentos numerados (keyword):
    e -- float, diferença mínima entre iterações para declarar que a formação finalmente convergiu 
    iter_ -- int/float, número de iterações
    
    Devolver:
    j_hist -- list/array com a evolução da função de custo durante a formação 
    theta -- array Numpy com o valor do theta na última iteração
    """
    
    iter_ = int(iter)  # Se declarou iter_ em notação científica (1e3) ou float (1000.), converter
    
    # Inicializar j_hist como uma list ou um array Numpy. Recordar que não sabemos que tamanho terá
    j_hist = []
    
    m, n = x.shape  # Obter m e n a partir das dimensões de X
    
    for k in range(iter_):  # Iterar sobre o número máximo de iterações
        theta_iter = np.copy(theta)  # Copiar theta para atualizar
        
        for j in range(n):  # Iterar sobre n.º de características
            # Atualizar theta_iter para cada característica, de acordo com a derivada da função de custo
            # Incluir a relação de formação alfa
            theta_iter[j] = theta[j] - (alpha / (m)) * np.sum((x.dot(theta) - y) * x[:, j])
        
        theta = theta_iter
            
        cost = cost_function(x, y, theta)  # Calcular o custo para a atual iteração theta
            
        j_hist.append(cost)  # Adicionar o custo da iteração atual ao histórico de custos
        
        # Comprovar se a diferença entre o custo da iteração atual e o custo da última iteração em valor 
        # absoluto são inferiores que a diferença mínima para declarar a convergência
        if k > 0 and abs(j_hist[-1] - j_hist[-2]) < e:
            print('Convergir na iteração n.º: ', k)
            break
    else:
        print('N.º máx. de iterações alcançado')
        
    return j_hist, theta

## TREINAR O DATASET

In [41]:
theta_ini = [50.5, 10.6, 5.9]
alpha = 0.1 
e = 1e-3
iter_ = 1e3 # Verificar se a sua função pode suportar valores de flutuação ou modificá-los.

j_hist, theta_final = gradient_descent(X, Y, theta_ini, alpha, e, iter_) 
# TODO: completar
print('\nTamanho da função de custo') 
print(len(j_hist))
print('\nÚltimos 10 valores da função de custo') 
print(j_hist[-10:])
print('\nCusto final:') 
print(round(j_hist[-1], 2)) 
print('\nTheta final:') 
print(theta_final)

N.º máx. de iterações alcançado

Tamanho da função de custo
1000

Últimos 10 valores da função de custo
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

Custo final:
nan

Theta final:
[nan nan nan]


C:\Users\SBUtilizador\AppData\Local\Temp\ipykernel_12992\2963629796.py:23: RuntimeWarning: overflow encountered in square
  j = (1 / (2 * m)) * np.sum((h - y) ** 2)
C:\Users\SBUtilizador\AppData\Local\Temp\ipykernel_12992\10088696.py:45: RuntimeWarning: invalid value encountered in scalar subtract
  if k > 0 and abs(j_hist[-1] - j_hist[-2]) < e:
C:\Users\SBUtilizador\AppData\Local\Temp\ipykernel_12992\10088696.py:35: RuntimeWarning: overflow encountered in multiply
  theta_iter[j] = theta[j] - (alpha / (m)) * np.sum((x.dot(theta) - y) * x[:, j])
